Algoritmo "semnome"

Var

user, password: caractere

Inicio

 escreva ("digite o seu usuário: ")
 leia(user)
 escreva ("digite a sua senha: ")
 leia (password)
 
 enquanto (user <> "admin") ou (password <> "admin") faca
          escreval ("Usuário ou senha inválidos")
          escreva ("digite o seu usuário: ")
          leia(user)
          escreva ("digite a sua senha: ")
          leia (password)
 fimenquanto

  escreval("seja bem vinda ao sistema")
Fimalgoritmo